Support for non-OpenAI models
fleet-ai/context pull request #3
Opened 2023-11-08 17:33 UTC by alexanderatallah

Love Context - fantastic idea!

This is just a suggestion PR in case you want to add support for hosted, non-OpenAI models (https://openrouter.ai), including CodeLlama. It also enables free (er, 100% discounted) inference, if you want to use Mistral 7B or Zephyr 7B.

Making this PR in part so I can use context with my openrouter models, and in part to hear your feedback

2023-11-08 19:35 UTC, jamino30 commented
Also, don't forget to mention in the `README.md` that their `OPENAI_API_KEY` is being used and show how to set it up correctly to avoid errors.

2023-11-09 00:39 UTC, adrwz requested changes
This code looks great! Can you do a few things?

1. We've pushed a few changes today. Can you resolve merge conflicts & test again?
2. Can you add instructions on how to use OpenRouter to the README? Ideally right above the "Local Models" section

Cheers, & thank you for contributing!

2023-11-09 00:39 UTC, adrwz commented on cli.py
> +        For non-OpenAI models, you should set `OPENROUTER_API_KEY`, and optionally `OPENROUTER_APP_URL` and `OPENROUTER_APP_TITLE`.
Can you link to some instructions on how to use (where to get the API key/app url/app title)?

Ideally to the right sections in our README

2023-11-09 01:51 UTC, alexanderatallah commented on cli.py
> +        For non-OpenAI models, you should set `OPENROUTER_API_KEY`, and optionally `OPENROUTER_APP_URL` and `OPENROUTER_APP_TITLE`.
Will do. FYI, if people don't set these, you'll get ranked for tokens consumed on the openrouter homepage :)

2023-11-09 01:51 UTC, alexanderatallah commented on cli.py
> +        For non-OpenAI models, you should set `OPENROUTER_API_KEY`, and optionally `OPENROUTER_APP_URL` and `OPENROUTER_APP_TITLE`.
If a developer does set a referrer app url, then the developer will get ranked

2023-11-09 02:04 UTC, alexanderatallah commented
@adrwz Resolved your comments!

2023-11-09 06:02 UTC, adrwz commented
@alexanderatallah tested & made some changes, LMK what you think!

https://github.com/alexanderatallah/context/pull/1

2023-11-10 16:07 UTC, adrwz requested changes
@alexanderatallah tested & made some changes to your PR, LMK what you think!

- Calling openai.chatCompletion.create() no longer works w/ most recent openai package version (see https://github.com/fleet-ai/context/issues/1), and openai.chat.completions.create() is not compatible with OpenRouter, so I changed it to curl the URL
- We'll only ask for OpenRouter API keys if the user asks to use a non-OpenAI model

https://github.com/alexanderatallah/context/pull/1

2023-11-10 20:41 UTC, alexanderatallah commented
Just saw @adrwz - approving now

2023-11-10 20:53 UTC, merged

2023-11-10 20:53 UTC, adrwz commented
Merged! Ty for contributing 🙏